services:
  relay:
    image: erayatesdev/roomful:latest
    env_file:
      - path: .env
        required: false
    ports:
      - '${PORT:-8787}:${PORT:-8787}'
    pull_policy: always
    restart: always
