services:
  relay:
    image: cahoots/relay:latest
    environment:
      HOST: 0.0.0.0
      PORT: ${PORT:-8787}
      MAX_CONNECTIONS: ${MAX_CONNECTIONS:-1000}
      CAHOOTS_REDIS_URL: ${CAHOOTS_REDIS_URL:-}
    ports:
      - '${PORT:-8787}:${PORT:-8787}'
    pull_policy: always
    restart: always
