import { createRoom } from './room';
import { RoomfulError } from './roomful-error';

export { createRoom };
export { RoomfulError };
export type {
  AddAIPeerOptions,
  AgentIdentity,
  AgentState,
  AIPeer,
  AIPeerAgent,
  AIPeerContext,
  AIPeerEvent,
  HeuristicAgentOptions,
} from './ai-peer';
export {
  addAIPeer,
  AGENT_ACTION_PREFIX,
  AGENT_IDENTITY_KEY,
  AGENT_STATE_KEY,
  createHeuristicAgent,
  getAgentActions,
  getAgentIdentity,
  getAgentState,
  isAgentPeer,
} from './ai-peer';
export type { ActivityStorageAdapter } from './engines/activity-storage';
export {
  createLocalStorageActivityStorage,
  createMemoryActivityStorage,
} from './engines/activity-storage';
export type { CommentsStorageAdapter } from './engines/comments-storage';
export {
  createLocalStorageCommentsStorage,
  createMemoryCommentsStorage,
} from './engines/comments-storage';
export { parseRoomfulRecording, RECORDING_FORMAT_VERSION } from './engines/recording';
export type {
  SessionParticipant,
  SessionSummarizerOptions,
  SessionSummary,
} from './engines/session-summary';
export { summarizeSession } from './engines/session-summary';
export type {
  ActivityEngine,
  ActivityEntry,
  ActivityOptions,
  AgentApprovalEngine,
  AgentApprovalOptions,
  AgentProposal,
  AgentProposalStatus,
  AwarenessEngine,
  AwarenessSelection,
  AwarenessState,
  Comment,
  CommentAnchor,
  CommentsEngine,
  CommentsOptions,
  CommentThread,
  CommentThreadHandle,
  CursorBasePosition,
  CursorData,
  CursorEngine,
  CursorOptions,
  CursorPosition,
  CursorRenderOptions,
  DebugOptions,
  EncryptionOptions,
  EventEngine,
  EventOptions,
  FieldPresenceEngine,
  FieldPresenceState,
  HistoryEngine,
  HistoryOptions,
  LockAcquireOptions,
  LockEngine,
  LockState,
  Peer,
  PointerBeam,
  PointerEngine,
  PointerOptions,
  PointerRenderOptions,
  PointerStyle,
  PresenceData,
  PresenceEngine,
  ReconnectOptions,
  RecordingDirection,
  RecordingEngine,
  RecordingFrame,
  RecordingOptions,
  RecordingState,
  RelayAuthToken,
  ReplayEvent,
  ReplaySession,
  Room,
  RoomDiagnostics,
  RoomDiagnosticsDebug,
  RoomDiagnosticsEncryption,
  RoomDiagnosticsEvents,
  RoomDiagnosticsNetwork,
  RoomDiagnosticsPeers,
  RoomDiagnosticsPresence,
  RoomDiagnosticsState,
  RoomDiagnosticsTransport,
  RoomEventHandler,
  RoomEventMap,
  RoomEventName,
  RoomfulErrorCode,
  RoomfulRecording,
  RoomfulYjsProvider,
  RoomfulYjsProviderEventHandler,
  RoomfulYjsProviderEventMap,
  RoomfulYjsProviderEventName,
  RoomfulYjsProviderStatus,
  RoomOptions,
  RoomStatus,
  StateChangeMeta,
  StateEngine,
  StateOptions,
  TimelineEntry,
  TransportMode,
  Unsubscribe,
  ViewportEngine,
  ViewportOptions,
  ViewportState,
  WebRTCDataChannelOptions,
  WebRTCOptions,
  WebSocketOptions,
} from './types';
