import 'dart:convert';
import 'dart:io';

import 'package:roomful/roomful.dart';
import 'package:test/test.dart';

// Validates the Dart protocol layer against the shared cross-SDK vectors generated by
// `@roomful/core` (RFC-0001, #102). MessagePack vectors are skipped until the Dart codec
// lands (S05); the JSON vectors exercise negotiation and the v1/v2 envelope.

const int fixedTs = 1700000000000;

dynamic revive(dynamic value) {
  if (value is Map<String, dynamic>) {
    if (value.length == 1 && value.containsKey(r'$bin')) {
      return base64Decode(value[r'$bin'] as String).toList();
    }
    return value.map<String, dynamic>((key, v) => MapEntry(key, revive(v)));
  }
  if (value is List) {
    return value.map<dynamic>(revive).toList();
  }
  return value;
}

void main() {
  final fixturesFile = File('../../protocol-fixtures/core-vectors.json');
  final fixtures =
      jsonDecode(fixturesFile.readAsStringSync()) as Map<String, dynamic>;

  group('negotiation vectors', () {
    for (final raw in fixtures['negotiation'] as List<dynamic>) {
      final vector = raw as Map<String, dynamic>;
      test(vector['name'] as String, () {
        final local =
            ProtocolCapabilities.fromJson(vector['local'] as Map<String, dynamic>);
        final remoteJson = vector['remote'];
        final remote = remoteJson == null
            ? null
            : ProtocolCapabilities.fromJson(remoteJson as Map<String, dynamic>);

        final result = negotiateSession(
          local,
          remote,
          supportsBinary: vector['supportsBinary'] as bool,
        );

        final expected = vector['result'] as Map<String, dynamic>;
        expect(result.compatible, expected['compatible']);
        final expectedSession = expected['session'];
        if (expectedSession is Map<String, dynamic>) {
          expect(result.session?.toJson(), equals(expectedSession));
        }
      });
    }
  });

  group('json envelope vectors', () {
    for (final raw in fixtures['envelopes'] as List<dynamic>) {
      final vector = raw as Map<String, dynamic>;
      final session = vector['session'] as Map<String, dynamic>;
      if (session['codec'] != 'json') {
        continue;
      }

      test(vector['name'] as String, () {
        final wire = vector['text'] as String;
        final message = revive(vector['message']) as Map<String, dynamic>;

        // Decode the JS-produced wire; it must match the fixture message.
        final decoded = decodeJsonEnvelope(wire, now: () => fixedTs);
        expect(decoded.type, message['type']);
        expect(decoded.roomId, message['roomId']);
        expect(decoded.fromPeerId, message['fromPeerId']);
        expect(decoded.toPeerId, message['toPeerId']);
        expect(decoded.timestamp, message['timestamp']);
        expect(decoded.payload, equals(message['payload']));

        // Encode -> decode round-trips (order-independent).
        final protocolSession = ProtocolSession(
          version: session['version'] as int,
          codec: session['codec'] as String,
          legacy: session['legacy'] as bool,
        );
        final reDecoded = decodeJsonEnvelope(
          encodeJsonEnvelope(decoded, protocolSession),
          now: () => fixedTs,
        );
        expect(reDecoded.type, decoded.type);
        expect(reDecoded.payload, equals(decoded.payload));
      });
    }
  });
}
