import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:roomful/roomful.dart';
import 'package:test/test.dart';

// Validates the Dart protocol layer against the shared cross-SDK vectors generated by
// `@roomful/core` (RFC-0001, #102). MessagePack vectors are skipped until the Dart codec
// lands (S05); the JSON vectors exercise negotiation and the v1/v2 envelope.

const int fixedTs = 1700000000000;

dynamic revive(dynamic value) {
  if (value is Map<String, dynamic>) {
    if (value.length == 1 && value.containsKey(r'$bin')) {
      return base64Decode(value[r'$bin'] as String).toList();
    }
    return value.map<String, dynamic>((key, v) => MapEntry(key, revive(v)));
  }
  if (value is List) {
    return value.map<dynamic>(revive).toList();
  }
  return value;
}

void main() {
  final fixturesFile = File('../../protocol-fixtures/core-vectors.json');
  final fixtures =
      jsonDecode(fixturesFile.readAsStringSync()) as Map<String, dynamic>;

  group('negotiation vectors', () {
    for (final raw in fixtures['negotiation'] as List<dynamic>) {
      final vector = raw as Map<String, dynamic>;
      test(vector['name'] as String, () {
        final local =
            ProtocolCapabilities.fromJson(vector['local'] as Map<String, dynamic>);
        final remoteJson = vector['remote'];
        final remote = remoteJson == null
            ? null
            : ProtocolCapabilities.fromJson(remoteJson as Map<String, dynamic>);

        final result = negotiateSession(
          local,
          remote,
          supportsBinary: vector['supportsBinary'] as bool,
        );

        final expected = vector['result'] as Map<String, dynamic>;
        expect(result.compatible, expected['compatible']);
        final expectedSession = expected['session'];
        if (expectedSession is Map<String, dynamic>) {
          expect(result.session?.toJson(), equals(expectedSession));
        }
      });
    }
  });

  group('envelope vectors', () {
    for (final raw in fixtures['envelopes'] as List<dynamic>) {
      final vector = raw as Map<String, dynamic>;
      final session = vector['session'] as Map<String, dynamic>;
      final codec = session['codec'] as String;

      test(vector['name'] as String, () {
        final message = revive(vector['message']) as Map<String, dynamic>;

        // Decode the JS-produced wire; it must match the fixture message.
        final WireMessage decoded;
        if (codec == 'msgpack') {
          decoded = decodeMsgpackEnvelope(
            base64Decode(vector['wireBase64'] as String),
            now: () => fixedTs,
          );
        } else {
          decoded = decodeJsonEnvelope(vector['text'] as String, now: () => fixedTs);
        }

        expect(decoded.type, message['type']);
        expect(decoded.roomId, message['roomId']);
        expect(decoded.fromPeerId, message['fromPeerId']);
        expect(decoded.toPeerId, message['toPeerId']);
        expect(decoded.timestamp, message['timestamp']);
        expect(decoded.payload, equals(message['payload']));
      });
    }
  });

  group('round-trip', () {
    const jsonSession = ProtocolSession(version: 2, codec: 'json', legacy: false);
    const msgpackSession = ProtocolSession(version: 2, codec: 'msgpack', legacy: false);

    test('json envelope encode then decode', () {
      final message = WireMessage(
        type: 'event',
        roomId: 'room-a',
        fromPeerId: 'peer-a',
        timestamp: fixedTs,
        payload: <String, dynamic>{
          'name': 'ping',
          'payload': <String, dynamic>{'ok': true},
        },
      );
      final decoded = decodeJsonEnvelope(
        encodeJsonEnvelope(message, jsonSession),
        now: () => fixedTs,
      );
      expect(decoded.type, 'event');
      expect(decoded.payload, equals(message.payload));
    });

    test('msgpack envelope encode then decode, with binary', () {
      final message = WireMessage(
        type: 'crdt:sync',
        roomId: 'room-a',
        fromPeerId: 'peer-a',
        timestamp: fixedTs,
        payload: <String, dynamic>{
          'kind': 'update',
          'data': Uint8List.fromList(<int>[9, 8, 7]),
        },
      );
      final decoded = decodeMsgpackEnvelope(
        encodeMsgpackEnvelope(message, msgpackSession),
        now: () => fixedTs,
      );
      expect(decoded.type, 'crdt:sync');
      expect((decoded.payload as Map<String, dynamic>)['data'], equals(<int>[9, 8, 7]));
    });
  });
}
