name: Flutter

on:
  push:
    branches: [main]
    paths:
      - 'dart/roomful_flutter/**'
      - 'dart/roomful/**'
      - '.github/workflows/flutter.yml'
  pull_request:
    paths:
      - 'dart/roomful_flutter/**'
      - 'dart/roomful/**'
      - '.github/workflows/flutter.yml'

jobs:
  roomful-flutter:
    name: roomful_flutter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dart/roomful_flutter
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
